micronaut:
  application:
    name: inventory_management
  server:
    cors:
      enabled: true
      origins: "*"
      methods: "*"
      headers: "*"
      exposed-headers: "*"
      allow-credentials: true
      max-age: 3600
    http:
      compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
        minimum-response-size: 1024
        strategies:
          - gzip
          - deflate
netty:
  default:
    allocator:
      max-order: 3
